language: node_js
os:
  - linux
dist: focal  
node_js:
  - "14"  

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  local_dir: build
  token: $GITHUB_TOKEN
  on:
    branch: main
