language: node_js
os:
  - linux
dist: xenial
node_js:
  - stable

deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  local_dir: build
  token: $GITHUB_TOKEN
  on:
    branch: 
      - main
